### ISSUE TITLE
The baseUrl parameter on AvataaarPicture.builder doesn't do anything.

### ISSUE THREAD

**Issue by joranmulderij** [frananleo/flutter_avataaar#2]
AvataaarPicture.builder's baseUrl parameter is just completely ignored and the baseUrl parameter from the given avatar is used.

BTW thanks for this package!

**Comment by frananleo** [comment]
Hi Joran, BaseUrl is not completely ignored, it must be defined when class is intanciated(see Avataaar)

```
class Avataaar implements AvataaarPart {
  final String baseUrl;
  final Top top;
  final Clothes clothes;
  final Eyes eyes;
  final Eyebrow eyebrow;
  final Mouth mouth;
  final Skin skin;
  final Style style;
  Color backgroundColor;

  Avataaar({
    this.baseUrl = AvataaarsApi.baseUrl,
    required this.top,
    required this.clothes,
    required this.eyes,
    required this.eyebrow,
    required this.mouth,
    required this.skin,
    required this.style,
    this.backgroundColor = AvataaarsApi.baseBackgroundColor,
  });
```

Avataaar.toUrl() is used once the Avataaar class is defined, and it uses the parameters on it.
AvataaarPicture should not used it. it will be removed :)
