### ISSUE TITLE
How to rename the name of the image ?

### ISSUE THREAD

**Issue by monikkacha** [frananleo/flutter_avataaar#4]
Hello , Thank you for creating such a great library.

experimenting with plugin and got to know that when download the image , it gets store like **c9b30e8d-92d5-4575-a552-4a7f8e62a72c.png**  

is there any option to set name for the image as need to implement the functionality

**Comment by frananleo** [comment]
Hi, I have updated the package to 0.1.14. In this release, The file can be saved using 
` Future<File> getPngFromSvg({
    String? path,
    String? fileName,
    double? width,
    double? height,
    bool overrideFile = false,
  })`
With the overrideFile flag previous file will be overrided(true) or if it exists will throw an error(false).
